### ISSUE TITLE
Please add a screen shot and license file

### ISSUE THREAD

**Issue by unixorn** [samuelb/samshell#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with screen shots so that users can see what they look like without having to install them.

Also, please add a license, some people won't use any code that doesn't have an open source license. If you don't have one in mind, https://choosealicense.com is a good resource to help you select an appropriate one.

**Comment by samuelb** [comment]
Hey. I added a picture and licence information.

Feel free to add this theme to your collection.

**Comment by unixorn** [comment]
Thanks, adding it
